<a href="https://colab.research.google.com/github/miguel-duque06/exercicios_introducao_ciencia_dados/blob/main/Exercicios_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***
## **Introdução a Ciência de Dados**


**Exercícios Pandas**
***

<br>

Neste notebook vamos explorar vários comandos necessários para conhecer os dados que iremos consumir.

Abaixo de cada orientação, crie uma célula para executar o código python que responde ao item.

Bons estudos!!!!

1. Importe as bibliotecas necessárias

In [ ]:
import pandas as pd

In [ ]:
url = '/content/Vendas.csv'
df_vendas = pd.read_csv(url)

2. Crie o DataFrame Pandas com o nome `df_vendas` a partir dos dados presentes no seguinte endereço:

https://raw.githubusercontent.com/alexvaroz/data_science_alem_do_basico/master/Vendas.csv

3. Mostre os primeiros 10 registros do DataFrame

In [ ]:
df_vendas.head(11)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,01/01/2019,Iguatemi Esplanada,Sapato Estampa,1,358.0,358.0
1,1,01/01/2019,Iguatemi Esplanada,Camiseta,2,180.0,360.0
2,1,01/01/2019,Iguatemi Esplanada,Sapato Xadrez,1,368.0,368.0
3,2,02/01/2019,Norte Shopping,Relógio,3,200.0,600.0
4,2,02/01/2019,Norte Shopping,Chinelo Liso,1,71.0,71.0
5,3,02/01/2019,Rio Mar Shopping Fortaleza,Cinto Linho,1,248.0,248.0
6,5,02/01/2019,Shopping Barra,Calça,1,170.0,170.0
7,6,02/01/2019,Shopping Ibirapuera,Polo Listrado,4,149.0,596.0
8,7,02/01/2019,Norte Shopping,Camisa Gola V Listrado,1,116.0,116.0
9,7,02/01/2019,Norte Shopping,Camisa Liso,1,105.0,105.0
10,8,02/01/2019,Iguatemi Campinas,Terno Estampa,5,706.0,3530.0

4. Quantos registros o dataframe possui?

In [ ]:
len(df_vendas)

93910

5. Qual o número de colunas do dataframe?

In [ ]:
len(df_vendas.columns)

7

6. Mostre o nome das colunas do dataframe.

In [ ]:
df_vendas.columns

Index(['Código Venda', 'Data', 'ID Loja', 'Produto', 'Quantidade',
       'Valor Unitário', 'Valor Final'],
      dtype='object')

7. Qual o item com maior preço unitário?

In [ ]:
df_vendas['Valor Unitário'].max()

750.0

8. Quantas lojas fazem parte da rede?

In [ ]:
df_vendas['ID Loja'].nunique()

25

9. Mostre o nome de todas as lojas.

In [ ]:
df_vendas['ID Loja'].unique()

array(['Iguatemi Esplanada', 'Norte Shopping',
       'Rio Mar Shopping Fortaleza', 'Shopping Barra',
       'Shopping Ibirapuera', 'Iguatemi Campinas',
       'Shopping Center Leste Aricanduva', 'Passei das Águas Shopping',
       'Shopping Recife', 'Shopping Midway Mall', 'Bourbon Shopping SP',
       'Shopping Center Interlagos', 'Parque Dom Pedro Shopping',
       'Center Shopping Uberlândia', 'Shopping União de Osasco',
       'Shopping Eldorado', 'Shopping Vila Velha',
       'Novo Shopping Ribeirão Preto', 'Rio Mar Recife',
       'Palladium Shopping Curitiba', 'Shopping SP Market',
       'Ribeirão Shopping', 'Shopping Iguatemi Fortaleza',
       'Shopping Morumbi', 'Salvador Shopping'], dtype=object)

10. Quantos itens foram vendidos no total?

In [ ]:
df_vendas['Quantidade'].sum()

np.int64(203461)

11. Qual o preço médio dos produtos da loja?

In [ ]:
df_vendas['Valor Unitário'].mean()

np.float64(191.72588648706207)

12. Qual o foi a receita total da loja 'Norte Shopping'?

In [ ]:
df_vendas[df_vendas['ID Loja'] == 'Norte Shopping']['Valor Final'].sum()

np.float64(1610477.0)

**Elabore mais 6 questões e as responda com os dados.**

13. Qual foi o produto teve mais pedidos?

In [ ]:
df_vendas.groupby('Produto')['Quantidade'].sum()

Produto
Bermuda             1692
Bermuda Estampa     1616
Bermuda Linho       1893
Bermuda Liso        1637
Bermuda Listrado    1675
                    ...
Tênis Estampa       1663
Tênis Linho         1713
Tênis Liso          1656
Tênis Listrado      1737
Tênis Xadrez        1661
Name: Quantidade, Length: 120, dtype: int64

14. Qual foi o faturamento de cada produto?

In [ ]:
df_vendas.groupby('Produto')['Valor Final'].sum().sort_values(ascending=False)

Produto
Terno Listrado    1215935.0
Terno Linho       1203000.0
Terno Liso        1199520.0
Terno Xadrez      1169850.0
Terno Estampa     1135954.0
                    ...
Meia Estampa        88400.0
Meia Xadrez         64944.0
Meia Liso           62358.0
Meia Listrado       59496.0
Meia                51450.0
Name: Valor Final, Length: 120, dtype: float64

15. Qual loja teve o maior faturamento?

In [ ]:
df_vendas.groupby('ID Loja')['Valor Final'].sum().sort_values(ascending=False)

ID Loja
Shopping Vila Velha                 1615271.0
Iguatemi Campinas                   1612460.0
Shopping SP Market                  1610930.0
Norte Shopping                      1610477.0
Palladium Shopping Curitiba         1600499.0
Bourbon Shopping SP                 1600260.0
Shopping Center Leste Aricanduva    1596714.0
Iguatemi Esplanada                  1596339.0
Ribeirão Shopping                   1594186.0
Rio Mar Recife                      1582897.0
Novo Shopping Ribeirão Preto        1578522.0
Rio Mar Shopping Fortaleza          1570540.0
Shopping Iguatemi Fortaleza         1550642.0
Shopping Barra                      1549955.0
Shopping União de Osasco            1547738.0
Center Shopping Uberlândia          1543961.0
Passei das Águas Shopping           1536925.0
Shopping Center Interlagos          1536665.0
Shopping Ibirapuera                 1527153.0
Shopping Eldorado                   1523772.0
Salvador Shopping                   1517583.0
Parque Dom Pedro Shopping           1509575.0
Shopping Recife                     1493008.0
Shopping Midway Mall                1485172.0
Shopping Morumbi                    1468508.0
Name: Valor Final, dtype: float64

16. Qual a data teve mais vendas?

In [ ]:
df_vendas.groupby('Data')['Valor Final'].sum().sort_values(ascending=False)

Data
22/09/2019    138521.0
19/04/2019    136527.0
24/10/2019    133262.0
24/04/2019    133160.0
15/06/2019    133062.0
                ...
04/09/2019    100512.0
24/05/2019    100266.0
01/06/2019     99367.0
27/03/2019     94331.0
01/01/2019      1086.0
Name: Valor Final, Length: 334, dtype: float64

17. Qual é o valor mais alto na coluna Valor Final?

In [ ]:
df_vendas['Valor Final'].max()

3750.0

18. Existe alguma loja que vende mais produtos caros que as outras?

In [ ]:
df_vendas.groupby('ID Loja')['Valor Unitário'].mean().sort_values(ascending=False)

ID Loja
Iguatemi Esplanada                  195.940355
Rio Mar Recife                      195.384409
Parque Dom Pedro Shopping           194.403654
Ribeirão Shopping                   194.288783
Shopping Barra                      194.012966
Iguatemi Campinas                   192.877406
Center Shopping Uberlândia          192.824131
Passei das Águas Shopping           192.764214
Shopping Iguatemi Fortaleza         192.672474
Shopping SP Market                  192.660977
Shopping Midway Mall                192.447457
Bourbon Shopping SP                 192.280418
Shopping União de Osasco            192.044732
Shopping Center Interlagos          191.761614
Norte Shopping                      191.036697
Shopping Recife                     190.517892
Rio Mar Shopping Fortaleza          190.503138
Novo Shopping Ribeirão Preto        190.330446
Shopping Eldorado                   190.134127
Salvador Shopping                   189.882242
Shopping Vila Velha                 189.670902
Shopping Center Leste Aricanduva    189.504530
Shopping Morumbi                    189.011494
Palladium Shopping Curitiba         189.002302
Shopping Ibirapuera                 187.618317
Name: Valor Unitário, dtype: float64